# OpenUPM azure pipelines

trigger: none

variables:
  # repo_url:
  # repo_branch:
  repodir: repo
  registry_addr: http://package.openupm.com

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo repo_url: $(repo_url)
    echo repo_branch: $(repo_branch)
    echo build_tag: $(build_tag)
    echo registry_addr: $(registry_addr)
  displayName: 'Print environment'

- powershell: |
    Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
    Write-Host "##vso[task.complete result=Canceled;]DONE"
  condition: and(succeeded(), or(eq(variables['repo_url'], ''), eq(variables['repo_branch'], '')))
  displayName: 'Verify environment'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DeleteFiles@1
  inputs:
    contents: $(repo_url)
  displayName: 'Clean target folder'

- script: |
    echo 'registry=$(registry_addr)' > .npmrc
    cat .npmrc
  displayName: 'Prepare .npmrc'

- script: |
    git clone --depth 1 --branch $(repo_branch) $(repo_url) $(repodir)
    cd $(repodir)
  displayName: 'Clone target repository'

# - task: npmAuthenticate@0
#   inputs:
#     customEndpoint: openupm
#     workingFile: '.npmrc'

- task: Npm@1
  inputs:
     command: custom
     workingDir: $(repodir)
     customCommand: 'publish --tag=$(build_tag) --registry=$(registry_addr)'
     customEndpoint: openupm
    #  publishRegistry: useExternalRegistry
    #  publishEndpoint: openupm
     verbose: true
  displayName: 'Publish to OpenUPM'
