# OpenUPM azure pipelines

trigger: none

variables:
  # repo_url:
  # repo_branch:
  repodir: repo
  registry_addr: http://package.openupm.com
  test_var: foo

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo repodir: $(repodir)
    echo registry_addr: $(registry_addr)
    echo repo_url: $(repo_url)
    echo repo_branch: $(repo_branch)
    echo build_tag: $(build_tag)
    echo test_var: $(test_var)
  displayName: 'Print environment'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['repo_url'], ''))
  displayName: 'Check variable repo_url'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['repo_branch'], ''))
  displayName: 'Check variable repo_branch'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['build_tag'], ''))
  displayName: 'Check variable build_tag'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DeleteFiles@1
  inputs:
    contents: $(repo_url)
  displayName: 'Clean target folder'

- script: |
    echo before: $(test_var)
    echo "##vso[task.setvariable variable=test_var;]foo"
    echo after: $(test_var)
  displayName: 'test var'

- script: |
    git clone --depth 1 --branch $(repo_branch) $(repo_url) $(repodir)
    cd $(repodir)
  displayName: 'Clone target repository'

- task: Npm@1
  inputs:
     command: custom
     workingDir: $(repodir)
     customCommand: 'publish --tag=$(build_tag) --registry=$(registry_addr)'
     customEndpoint: openupm
  displayName: 'Publish to OpenUPM'
