# OpenUPM azure pipelines

trigger: none

variables:
  # repo_url:
  # repo_branch:
  # package_name:
  repodir: repo
  registry_addr: http://package.openupm.com
  build_tag: latest

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo repodir: $(repodir)
    echo registry_addr: $(registry_addr)
    echo repo_url: $(repo_url)
    echo repo_branch: $(repo_branch)
    echo package_name: $(package_name)
  displayName: 'Print environment'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['repo_url'], ''))
  displayName: 'Check variable repo_url'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['repo_branch'], ''))
  displayName: 'Check variable repo_branch'

- powershell: |
    exit 1
  condition: and(succeeded(), eq(variables['package_name'], ''))
  displayName: 'Check variable package_name'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
  displayName: 'Install dependencies'

- script: |
    latest_ver=`npm --registry=$(registry_addr) show $(package_name) version` || latest_ver=0.0.0
    echo $latest_ver
  displayName: 'Get dist tag'

- task: DeleteFiles@1
  inputs:
    contents: $(repodir)
  displayName: 'Clean target folder'

- script: |
    git clone --depth 1 --branch $(repo_branch) $(repo_url) $(repodir)
    cd $(repodir)
  displayName: 'Clone target repository'

- task: Npm@1
  inputs:
    command: custom
    workingDir: $(repodir)
    customCommand: 'publish --tag=$(build_tag) --registry=$(registry_addr)'
    customEndpoint: openupm
  displayName: 'Publish to OpenUPM with tag'
